name: refactoring
description: Refactoring code example with dart
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  yaml: 
  yaml_writer:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
